/**
 * Default content — imported from the legacy static site (jameskamz.github.io),
 * the CV, and the 2026 positioning brief.
 *
 * Used in two places:
 *  - `prisma/seed.ts` writes it to the database;
 *  - `src/lib/content.ts` serves it as a fallback when no database is reachable
 *    (local preview, CI builds), so the public site always renders.
 */
import { defaultPricing } from "@/lib/budget";
import type {
  ExperienceView,
  FaqView,
  ProjectView,
  ServiceView,
  SettingsView,
  SkillGroupView,
  StatView,
  TestimonialView,
} from "@/lib/types";

export const defaultChatbotInstructionsFr = `Tu es l'assistant du portfolio de James Kamz (Koffi Jacques Amouzou), SaaS builder, ingénieur full-stack, développeur Odoo et expert en automatisation.
- Réponds de façon concise, chaleureuse et professionnelle, en français.
- Aide les visiteurs à comprendre les services, les projets réalisés et la façon de travailler de James.
- Pour toute question de prix, donne uniquement des ordres de grandeur indicatifs et oriente vers l'estimateur de budget (/budget) puis vers un échange direct.
- Propose de laisser ses coordonnées (formulaire de contact /contact) dès que le visiteur a un projet concret.`;

export const defaultChatbotInstructionsEn = `You are the portfolio assistant of James Kamz (Koffi Jacques Amouzou), SaaS builder, full-stack engineer, Odoo developer and automation expert.
- Answer concisely, warmly and professionally, in English.
- Help visitors understand James's services, past projects and way of working.
- For pricing questions, only give indicative ballpark figures and point to the budget estimator (/en/budget), then to a direct conversation.
- Suggest leaving contact details (contact form /en/contact) as soon as the visitor has a concrete project.`;

export const defaultSettings: SettingsView = {
  id: "main",
  fullName: "Koffi Jacques Amouzou",
  alias: "James Kamz",
  titlesFr: ["SaaS Builder", "Full-Stack Engineer", "Odoo Developer", "Automation Expert"],
  titlesEn: ["SaaS Builder", "Full-Stack Engineer", "Odoo Developer", "Automation Expert"],
  taglineFr:
    "Je transforme vos idées en SaaS rentables, j'intègre et personnalise Odoo, et j'automatise vos processus métiers pour faire gagner du temps — et de l'argent — à votre entreprise.",
  taglineEn:
    "I turn ideas into profitable SaaS products, integrate and tailor Odoo, and automate business processes so your company saves time — and money.",
  aboutFr: [
    "Je suis Koffi Jacques Amouzou, aussi connu sous le nom de James Kamz. Ingénieur full-stack depuis plus de 5 ans, je conçois des produits SaaS, des applications web robustes et des intégrations Odoo adaptées aux besoins concrets des entreprises.",
    "Mon parcours combine le développement web, l'intégration ERP, l'automatisation et une forte attention à la qualité technique. Je travaille avec Python (Django, FastAPI), Next.js/React, Angular et PostgreSQL pour construire des solutions fiables, sécurisées et durables.",
    "Je m'intéresse aussi à la cybersécurité et au data engineering, pour concevoir des systèmes plus sûrs et mieux exploiter les données.",
    "Mon objectif est simple : livrer des solutions utiles, claires et solides qui apportent une vraie valeur au quotidien.",
  ].join("\n\n"),
  aboutEn: [
    "I'm Koffi Jacques Amouzou, also known as James Kamz. A full-stack engineer for over 5 years, I build SaaS products, robust web applications and Odoo integrations tailored to real business needs.",
    "My background blends web development, ERP integration, automation and a strong focus on engineering quality. I work with Python (Django, FastAPI), Next.js/React, Angular and PostgreSQL to ship reliable, secure and long-lasting solutions.",
    "I'm also into cybersecurity and data engineering, to design safer systems and make better use of data.",
    "My goal is simple: deliver useful, clear and solid solutions that bring real value every day.",
  ].join("\n\n"),
  // TODO(owner): set the city from the admin (Paramètres) — e.g. "Casablanca, Maroc".
  locationFr: "Maroc",
  locationEn: "Morocco",
  available: true,
  availabilityFr: "Disponible en freelance · remote dans le monde entier",
  availabilityEn: "Available for freelance · remote worldwide",
  email: "jameskamzk@gmail.com",
  phone: null,
  whatsapp: null,
  linkedin: "https://www.linkedin.com/in/james-kamz/",
  github: "https://github.com/JamesKamz",
  youtube: "https://www.youtube.com/@JamesKamz",
  youtubeHandle: "JamesKamz",
  facebook: "https://www.facebook.com/jamesonekamz",
  instagram: "https://www.instagram.com/jameskamzk/",
  comeup: "https://comeup.com/fr/@kamzjames",
  upwork: "https://www.upwork.com/freelancers/~01a82a13afeddb700e",
  comeupSince: 2023,
  photoUrl: "/images/profile/james-kamz.webp",
  cvFrUrl: "/cv/cv-james-kamz-fr.pdf",
  cvEnUrl: null,
  chatbotEnabled: true,
  chatbotInstructionsFr: defaultChatbotInstructionsFr,
  chatbotInstructionsEn: defaultChatbotInstructionsEn,
  pricing: defaultPricing,
};

/**
 * Key figures. Only values backed by the legacy site / brief are visible by default;
 * the others must be filled in from the admin before being shown.
 */
export const defaultStats: StatView[] = [
  { id: "stat-years", key: "years", labelFr: "Années d'expérience", labelEn: "Years of experience", value: 5, prefix: "", suffix: "+", decimals: 0, visible: true, order: 0 },
  { id: "stat-projects", key: "projects", labelFr: "Projets livrés", labelEn: "Projects delivered", value: 10, prefix: "", suffix: "+", decimals: 0, visible: true, order: 1 },
  { id: "stat-clients", key: "clients", labelFr: "Clients satisfaits", labelEn: "Happy clients", value: 0, prefix: "", suffix: "+", decimals: 0, visible: false, order: 2 },
  { id: "stat-rating", key: "rating", labelFr: "Note moyenne", labelEn: "Average rating", value: 5, prefix: "", suffix: "/5", decimals: 1, visible: false, order: 3 },
  { id: "stat-youtube", key: "youtubeSubscribers", labelFr: "Abonnés YouTube", labelEn: "YouTube subscribers", value: 0, prefix: "", suffix: "", decimals: 0, visible: false, order: 4 },
];

export const defaultServices: ServiceView[] = [
  {
    id: "svc-saas",
    slug: "saas",
    icon: "rocket",
    titleFr: "SaaS sur mesure",
    titleEn: "Custom SaaS",
    descFr:
      "Du MVP à la production : cadrage, architecture multi-tenant, abonnements, tableaux de bord et mise en ligne. Un produit pensé pour être rentable dès les premiers clients.",
    descEn:
      "From MVP to production: scoping, multi-tenant architecture, subscriptions, dashboards and launch. A product designed to be profitable from the first customers.",
    tags: ["MVP", "Stripe", "Multi-tenant", "Next.js", "FastAPI"],
    size: "lg",
    published: true,
    order: 0,
  },
  {
    id: "svc-fullstack",
    slug: "fullstack",
    icon: "layers",
    titleFr: "Développement Full-Stack",
    titleEn: "Full-Stack Development",
    descFr:
      "Applications web fiables, modernes et évolutives avec Django, FastAPI, Next.js, React et Angular — du back-office au front soigné.",
    descEn:
      "Reliable, modern and scalable web applications with Django, FastAPI, Next.js, React and Angular — from back office to polished front end.",
    tags: ["Django", "Next.js", "React", "Angular", "PostgreSQL"],
    size: "md",
    published: true,
    order: 1,
  },
  {
    id: "svc-odoo",
    slug: "odoo",
    icon: "boxes",
    titleFr: "Odoo",
    titleEn: "Odoo",
    descFr:
      "Intégration, développement et personnalisation de modules, migration de versions, maintenance et supervision pour optimiser vos processus métiers.",
    descEn:
      "Integration, custom module development, version migrations, maintenance and monitoring to streamline your business processes.",
    tags: ["Intégration", "Modules", "Migration", "Maintenance"],
    size: "md",
    published: true,
    order: 2,
  },
  {
    id: "svc-automation",
    slug: "automation",
    icon: "workflow",
    titleFr: "Automatisation",
    titleEn: "Automation",
    descFr:
      "Workflows n8n, Make ou Zapier, scripts Python et intégrations API : les tâches répétitives disparaissent, vos équipes se concentrent sur l'essentiel.",
    descEn:
      "n8n, Make or Zapier workflows, Python scripts and API integrations: repetitive tasks disappear so your team can focus on what matters.",
    tags: ["n8n", "Make", "Zapier", "Python", "Webhooks"],
    size: "lg",
    published: true,
    order: 3,
  },
  {
    id: "svc-api",
    slug: "api",
    icon: "braces",
    titleFr: "API & Backend",
    titleEn: "API & Backend",
    descFr:
      "API REST sécurisées avec Django REST Framework ou FastAPI, modélisation des données et connexion fluide avec vos interfaces et services.",
    descEn:
      "Secure REST APIs with Django REST Framework or FastAPI, data modelling and seamless connections with your interfaces and services.",
    tags: ["REST", "DRF", "FastAPI", "Auth", "Docs"],
    size: "sm",
    published: true,
    order: 4,
  },
  {
    id: "svc-wordpress",
    slug: "wordpress",
    icon: "shield",
    titleFr: "WordPress & sécurité",
    titleEn: "WordPress & security",
    descFr:
      "Sites WordPress professionnels, optimisation, maintenance et durcissement sécurité pour des projets durables.",
    descEn:
      "Professional WordPress sites, optimisation, maintenance and security hardening for long-lasting projects.",
    tags: ["WordPress", "Performance", "Hardening"],
    size: "sm",
    published: true,
    order: 5,
  },
];

type P = Omit<ProjectView, "id"> & { id?: string };
const project = (p: P): ProjectView => ({ ...p, id: p.id ?? `prj-${p.slug}` });

export const defaultProjects: ProjectView[] = [
  project({
    slug: "ele-afrika",
    titleFr: "Ele Afrika",
    titleEn: "Ele Afrika",
    summaryFr: "Plateforme de print on demand pour créateurs et boutiques africaines, avec Next.js & Django.",
    summaryEn: "Print-on-demand platform for African creators and shops, built with Next.js & Django.",
    problemFr:
      "Les créateurs voulaient vendre des produits personnalisés sans gérer stock, impression ni logistique, et sans outil adapté à leur marché.",
    problemEn:
      "Creators wanted to sell custom products without handling stock, printing or logistics — and without a tool suited to their market.",
    solutionFr:
      "Une plateforme où chaque créateur ouvre sa boutique, personnalise ses produits et reçoit ses commandes, adossée à une API Django dédiée et un front Next.js performant.",
    solutionEn:
      "A platform where each creator opens a shop, customises products and receives orders, backed by a dedicated Django API and a fast Next.js front end.",
    resultFr: "Plateforme en production sur eleafrika.com, servie par sa propre API REST.",
    resultEn: "Platform live at eleafrika.com, powered by its own REST API.",
    categories: ["SAAS", "WEB"],
    stack: ["Next.js", "Django", "Django REST Framework", "PostgreSQL"],
    liveUrl: "https://eleafrika.com/",
    repoUrl: null,
    coverImage: "/images/projects/ele-afrika.webp",
    gallery: ["/images/projects/ele-afrika.webp", "/images/projects/ele-afrika-api.webp"],
    year: 2025,
    featured: true,
    published: true,
    order: 0,
  }),
  project({
    slug: "ele-afrika-api",
    titleFr: "Ele Afrika API",
    titleEn: "Ele Afrika API",
    summaryFr: "API RESTful pour la gestion des boutiques, des produits personnalisés et des commandes.",
    summaryEn: "RESTful API managing shops, customised products and orders.",
    problemFr: "Le front, le back-office et les partenaires d'impression devaient partager une source de vérité unique et sécurisée.",
    problemEn: "The storefront, back office and printing partners needed a single, secure source of truth.",
    solutionFr: "Une API Django REST Framework structurée autour des boutiques, produits, variantes et commandes, documentée et sécurisée.",
    solutionEn: "A Django REST Framework API structured around shops, products, variants and orders — documented and secured.",
    resultFr: "API en production sur api.eleafrika.com, consommée par la plateforme Ele Afrika.",
    resultEn: "API live at api.eleafrika.com, consumed by the Ele Afrika platform.",
    categories: ["API"],
    stack: ["Django", "Django REST Framework", "PostgreSQL"],
    liveUrl: "https://api.eleafrika.com/",
    repoUrl: null,
    coverImage: "/images/projects/ele-afrika-api.webp",
    gallery: ["/images/projects/ele-afrika-api.webp"],
    year: 2025,
    featured: false,
    published: true,
    order: 1,
  }),
  project({
    slug: "arbre-a-palabre",
    titleFr: "Arbre à palabre",
    titleEn: "Arbre à palabre",
    summaryFr: "Plateforme citoyenne autour de la transparence et du dialogue local dans le secteur extractif.",
    summaryEn: "Civic platform for transparency and local dialogue in the extractive sector.",
    problemFr: "Les communes et citoyens manquaient d'un espace commun pour suivre les informations et échanger autour des industries extractives.",
    problemEn: "Municipalities and citizens lacked a shared space to follow information and discuss the extractive industries.",
    solutionFr: "Une plateforme web Next.js & Django qui centralise l'information et ouvre le dialogue entre acteurs locaux.",
    solutionEn: "A Next.js & Django web platform that centralises information and opens dialogue between local stakeholders.",
    resultFr: "Plateforme en ligne sur communesextractives.org.",
    resultEn: "Platform live at communesextractives.org.",
    categories: ["WEB"],
    stack: ["Next.js", "Django", "PostgreSQL"],
    liveUrl: "https://communesextractives.org",
    repoUrl: null,
    coverImage: "/images/projects/arbre-a-palabre.webp",
    gallery: ["/images/projects/arbre-a-palabre.webp"],
    year: 2025,
    featured: true,
    published: true,
    order: 2,
  }),
  project({
    slug: "kondzimo",
    titleFr: "Kondzimo",
    titleEn: "Kondzimo",
    summaryFr: "Système intelligent d'orientation des patients vers l'établissement de santé le plus adapté.",
    summaryEn: "Smart system routing patients to the most suitable healthcare facility.",
    problemFr: "Les patients ne savent pas toujours vers quel établissement se tourner, ce qui surcharge certains centres et retarde la prise en charge.",
    problemEn: "Patients don't always know which facility to go to, overloading some centres and delaying care.",
    solutionFr: "Une application Next.js reliée à une API FastAPI qui recommande l'établissement le plus adapté selon les besoins du patient.",
    solutionEn: "A Next.js app backed by a FastAPI service that recommends the most suitable facility based on the patient's needs.",
    resultFr: "Prototype fonctionnel déployé et accessible en ligne.",
    resultEn: "Working prototype deployed and available online.",
    categories: ["WEB", "API"],
    stack: ["Next.js", "FastAPI", "Python"],
    liveUrl: "https://kondzimo-web.onrender.com/",
    repoUrl: null,
    coverImage: "/images/projects/kondzimo.webp",
    gallery: ["/images/projects/kondzimo.webp"],
    year: 2025,
    featured: true,
    published: true,
    order: 3,
  }),
  project({
    slug: "iblt",
    titleFr: "IBLT",
    titleEn: "IBLT",
    summaryFr: "Site de présentation pour un institut d'enseignement supérieur, réalisé avec Bootstrap.",
    summaryEn: "Showcase website for a higher-education institute, built with Bootstrap.",
    problemFr: "L'établissement avait besoin d'une présence web claire pour présenter ses formations.",
    problemEn: "The institute needed a clear web presence to present its programmes.",
    solutionFr: "Un site vitrine responsive en Bootstrap, simple à parcourir.",
    solutionEn: "A responsive Bootstrap showcase site that is easy to browse.",
    resultFr: "Site publié et accessible en ligne.",
    resultEn: "Site published and available online.",
    categories: ["WEB"],
    stack: ["Bootstrap", "HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://main--splendorous-muffin-db504a.netlify.app/",
    repoUrl: null,
    coverImage: "/images/projects/iblt.webp",
    gallery: ["/images/projects/iblt.webp"],
    year: 2023,
    featured: false,
    published: true,
    order: 4,
  }),
  project({
    slug: "openfarm",
    titleFr: "Openfarm",
    titleEn: "Openfarm",
    summaryFr: "Site de présentation réalisé pendant le Miabé Hackathon.",
    summaryEn: "Showcase website built during the Miabé Hackathon.",
    problemFr: "Présenter un projet agricole de façon convaincante en un temps très court, dans le cadre d'un hackathon.",
    problemEn: "Present an agricultural project convincingly in a very short time, as part of a hackathon.",
    solutionFr: "Un site vitrine conçu et livré pendant le Miabé Hackathon.",
    solutionEn: "A showcase site designed and shipped during the Miabé Hackathon.",
    resultFr: "Livré dans les délais du hackathon et publié en ligne.",
    resultEn: "Delivered within the hackathon timeframe and published online.",
    categories: ["WEB"],
    stack: ["HTML5", "CSS3", "JavaScript"],
    liveUrl: "https://open-farm.netlify.app/",
    repoUrl: null,
    coverImage: "/images/projects/openfarm.webp",
    gallery: ["/images/projects/openfarm.webp"],
    year: 2023,
    featured: false,
    published: true,
    order: 5,
  }),
  project({
    slug: "swipe-api",
    titleFr: "Swipe API",
    titleEn: "Swipe API",
    summaryFr: "API Django REST Framework disponible en code source.",
    summaryEn: "Open-source Django REST Framework API.",
    problemFr: "Disposer d'une base d'API propre et réutilisable pour une application de type « swipe ».",
    problemEn: "Provide a clean, reusable API foundation for a swipe-style application.",
    solutionFr: "Une API Django REST Framework structurée, publiée en open source sur GitHub.",
    solutionEn: "A well-structured Django REST Framework API, published open source on GitHub.",
    resultFr: "Code source disponible publiquement sur GitHub.",
    resultEn: "Source code publicly available on GitHub.",
    categories: ["API"],
    stack: ["Django", "Django REST Framework"],
    liveUrl: null,
    repoUrl: "https://github.com/JamesKamz/Swipe-API",
    coverImage: "/images/projects/swipe-api.webp",
    gallery: ["/images/projects/swipe-api.webp"],
    year: 2023,
    featured: false,
    published: true,
    order: 6,
  }),
  project({
    slug: "olive-shop",
    titleFr: "Olive Shop",
    titleEn: "Olive Shop",
    summaryFr: "Projet e-commerce développé avec Django, Bootstrap et PostgreSQL.",
    summaryEn: "E-commerce project built with Django, Bootstrap and PostgreSQL.",
    problemFr: "Mettre en place une boutique en ligne complète : catalogue, panier et commandes.",
    problemEn: "Build a complete online shop: catalogue, cart and orders.",
    solutionFr: "Une application Django avec catalogue, panier et gestion des commandes, interface Bootstrap.",
    solutionEn: "A Django application with catalogue, cart and order management, Bootstrap UI.",
    resultFr: "Code source disponible sur GitHub.",
    resultEn: "Source code available on GitHub.",
    categories: ["WEB"],
    stack: ["Django", "Bootstrap", "PostgreSQL"],
    liveUrl: null,
    repoUrl: "https://github.com/JamesKamz/Onlineshop",
    coverImage: "/images/projects/olive-shop.webp",
    gallery: ["/images/projects/olive-shop.webp"],
    year: 2023,
    featured: false,
    published: true,
    order: 7,
  }),
];

/**
 * Placeholder testimonials. NEVER published by default — replace them with
 * real reviews (ComeUp, Upwork, direct clients) from the admin.
 */
export const defaultTestimonials: TestimonialView[] = [
  {
    id: "tst-example-1",
    authorName: "EXEMPLE — à remplacer",
    authorRole: "Fondateur·rice d'une startup",
    country: "France",
    platform: "COMEUP",
    rating: 5,
    textFr: "EXEMPLE — à remplacer par un vrai avis client ComeUp avant publication.",
    textEn: "EXAMPLE — replace with a real ComeUp client review before publishing.",
    sourceUrl: "https://comeup.com/fr/@kamzjames",
    isExample: true,
    published: false,
    order: 0,
  },
  {
    id: "tst-example-2",
    authorName: "EXEMPLE — à remplacer",
    authorRole: "Responsable des opérations",
    country: "Canada",
    platform: "UPWORK",
    rating: 5,
    textFr: "EXEMPLE — à remplacer par un vrai avis client Upwork avant publication.",
    textEn: "EXAMPLE — replace with a real Upwork client review before publishing.",
    sourceUrl: "https://www.upwork.com/freelancers/~01a82a13afeddb700e",
    isExample: true,
    published: false,
    order: 1,
  },
];

export const defaultSkillGroups: SkillGroupView[] = [
  { id: "skg-backend", slug: "backend", icon: "server", nameFr: "Python & backend", nameEn: "Python & backend", items: ["Python", "Django", "FastAPI", "Django REST Framework", "Celery"], order: 0 },
  { id: "skg-frontend", slug: "frontend", icon: "monitor", nameFr: "Front-end", nameEn: "Front-end", items: ["Next.js", "React", "Angular", "TypeScript", "Tailwind CSS"], order: 1 },
  { id: "skg-data", slug: "data", icon: "database", nameFr: "Données", nameEn: "Data", items: ["SQL", "PostgreSQL", "MySQL", "Prisma", "Data engineering"], order: 2 },
  { id: "skg-odoo", slug: "odoo", icon: "boxes", nameFr: "ERP Odoo", nameEn: "Odoo ERP", items: ["Modules sur mesure", "Intégration", "Migration", "OWL / QWeb", "XML-RPC"], order: 3 },
  { id: "skg-automation", slug: "automation", icon: "workflow", nameFr: "Automatisation", nameEn: "Automation", items: ["n8n", "Make", "Zapier", "Scripts Python", "Webhooks & API"], order: 4 },
  { id: "skg-devops", slug: "devops", icon: "container", nameFr: "DevOps & serveurs", nameEn: "DevOps & servers", items: ["Docker", "GitHub Actions", "CI/CD", "Linux", "Nginx", "Administration serveur"], order: 5 },
  { id: "skg-design", slug: "design", icon: "pen-tool", nameFr: "Design", nameEn: "Design", items: ["Figma", "Canva", "Photoshop"], order: 6 },
  { id: "skg-security", slug: "security", icon: "shield", nameFr: "Cybersécurité", nameEn: "Cybersecurity", items: ["Google Cybersecurity Certificate", "Durcissement WordPress", "OWASP", "Sécurité des API"], order: 7 },
];

const d = (iso: string) => new Date(iso);

export const defaultExperiences: ExperienceView[] = [
  {
    id: "exp-freelance",
    kind: "WORK",
    roleFr: "Ingénieur full-stack & développeur Odoo freelance",
    roleEn: "Freelance full-stack engineer & Odoo developer",
    company: "ComeUp · Upwork · clients directs",
    descFr: "Conception de SaaS, applications web, intégrations Odoo et automatisations pour des clients en Afrique, en Europe et en Amérique du Nord.",
    descEn: "Building SaaS products, web apps, Odoo integrations and automations for clients across Africa, Europe and North America.",
    startDate: d("2023-01-01"),
    endDate: null,
    order: 0,
  },
  {
    id: "exp-ngstars-odoo",
    kind: "WORK",
    roleFr: "Développeur & intégrateur Odoo",
    roleEn: "Odoo developer & integrator",
    company: "NG-STARS",
    descFr: "Développement et personnalisation de modules Odoo, intégration chez les clients, maintenance.",
    descEn: "Developed and customised Odoo modules, client integrations and maintenance.",
    startDate: d("2024-02-01"),
    endDate: d("2024-10-31"),
    order: 1,
  },
  {
    id: "exp-hackathon",
    kind: "AWARD",
    roleFr: "Miabé Hackathon — finaliste 2023, lauréat 2024",
    roleEn: "Miabé Hackathon — 2023 finalist, 2024 winner",
    company: "Miabé Hackathon",
    descFr: "Conception et livraison de prototypes en temps limité, en équipe.",
    descEn: "Designed and shipped prototypes under time pressure, as a team.",
    startDate: d("2023-06-01"),
    endDate: d("2024-12-31"),
    order: 2,
  },
  {
    id: "exp-10000codeurs",
    kind: "WORK",
    roleFr: "Ambassadeur",
    roleEn: "Ambassador",
    company: "10.000 Codeurs",
    descFr: "Animation de la communauté et accompagnement de nouveaux développeurs.",
    descEn: "Community building and mentoring of new developers.",
    startDate: d("2023-08-01"),
    endDate: null,
    order: 3,
  },
  {
    id: "exp-ngstars-dev",
    kind: "WORK",
    roleFr: "Développeur (stage)",
    roleEn: "Developer (internship)",
    company: "NG-STARS",
    descFr: "Développement d'applications web au sein de l'équipe technique.",
    descEn: "Web application development within the engineering team.",
    startDate: d("2023-06-01"),
    endDate: d("2023-09-30"),
    order: 4,
  },
  {
    id: "exp-donservices",
    kind: "WORK",
    roleFr: "Développeur web (stage)",
    roleEn: "Web developer (internship)",
    company: "DON SERVICES",
    descFr: "Création et maintenance de sites web.",
    descEn: "Website creation and maintenance.",
    startDate: d("2023-03-01"),
    endDate: d("2023-05-31"),
    order: 5,
  },
  {
    id: "exp-iblt",
    kind: "EDUCATION",
    roleFr: "Licence professionnelle — Informatique industrielle et maintenance",
    roleEn: "Professional bachelor's — Industrial computing & maintenance",
    company: "Institut Supérieur Bilingue Libre du Togo (IBLT)",
    descFr: "Informatique industrielle, systèmes, réseaux et maintenance.",
    descEn: "Industrial computing, systems, networks and maintenance.",
    startDate: d("2020-10-01"),
    endDate: d("2023-07-31"),
    order: 6,
  },
];

export const defaultFaq: FaqView[] = [
  {
    id: "faq-process",
    questionFr: "Comment se déroule un projet ?",
    questionEn: "How does a project work?",
    answerFr: "Un appel de cadrage gratuit, un devis détaillé, puis des livraisons itératives (démo chaque semaine ou toutes les deux semaines) jusqu'à la mise en production et la maintenance.",
    answerEn: "A free scoping call, a detailed quote, then iterative deliveries (demo every week or two) up to production launch and maintenance.",
    published: true,
    order: 0,
  },
  {
    id: "faq-pricing",
    questionFr: "Combien coûte un projet ?",
    questionEn: "How much does a project cost?",
    answerFr: "Cela dépend du périmètre. L'estimateur de budget donne une fourchette indicative en MAD, EUR et USD ; le prix final est fixé dans un devis après échange.",
    answerEn: "It depends on scope. The budget estimator gives an indicative range in MAD, EUR and USD; the final price is set in a quote after we talk.",
    published: true,
    order: 1,
  },
  {
    id: "faq-remote",
    questionFr: "Travaillez-vous à distance ?",
    questionEn: "Do you work remotely?",
    answerFr: "Oui, je suis basé au Maroc et je travaille en remote avec des clients du monde entier, en français ou en anglais.",
    answerEn: "Yes — I'm based in Morocco and work remotely with clients worldwide, in French or English.",
    published: true,
    order: 2,
  },
  {
    id: "faq-odoo",
    questionFr: "Quelles versions d'Odoo maîtrisez-vous ?",
    questionEn: "Which Odoo versions do you work with?",
    answerFr: "Les versions récentes (Community et Enterprise), y compris les migrations entre versions et le développement de modules sur mesure.",
    answerEn: "Recent versions (Community and Enterprise), including version migrations and custom module development.",
    published: true,
    order: 3,
  },
];
